apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: go-app
# Defining the build stage
build:
  artifacts:
  - image: go-app
    docker:
      dockerfile: Dockerfile
# Defining the test stage
test:
  - image: go-app
    custom:
      - command: ./run_tests.sh
        timeoutSeconds: 60
        dependencies:
          paths:
          -  "*_test.go"
          -  "run_tests.sh"
# Defining the deployment stage
deploy:
  kubectl:
    manifests:
    - go-app-deployment.yaml
    - istio-config.yaml
